### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by 470projectlsr** [divyakraman/SS-SFDA-Self-Supervised-Source-Free-Domain-Adaptation-for-Road-Segmentation-in-Hazardous-Environme#1]
In line254 in train_stage3.py:

loss_seg2 = bce_loss(out[0,0,:,:],labels1)

why use labels1, is labels1 ground truth label?

**Comment by divyakraman** [comment]
Yes, it is the ground-truth label. In stage 3, we use a small subset (5-10 samples) of _annotated_ samples from the dataset for finetuning.
