### ISSUE TITLE
Cna't find: weatherDataSet

### ISSUE THREAD

**Issue by Siyuluan** [divyakraman/SS-SFDA-Self-Supervised-Source-Free-Domain-Adaptation-for-Road-Segmentation-in-Hazardous-Environme#2]
Hi,

Thank you for your code and paper! When I ran the code, I met one bug that can't find weatherDataSet.

IN train_stage2step1.py  Line 22: from dataset.weather import weatherDataSet

Do you know how to fix it?

Thanks!

**Comment by divyakraman** [comment]
Hello, 

The 'weatherDataSet' is a proxy name for any dataloader you write for specific adverse weather datasets. Our datasets folders contains dataloaders for the datasets we've used in the paper, feel free to modify the name for any dataset you would like to use. These dataloaders can also be used as a sample for writing your own dataloaders for any new datasets that you wish to run experiments on.

Thanks!
